import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <NavBar />
        <main>{children}</main>
   
        <footer className="text-center pt-8 pb-10 border-t border-zinc-800">
          <p className="text-sm text-zinc-500">
           Todos los derechos reservados &copy; BarTuc360 2026
          </p>
          <p className="text-zinc-400 mt-2 font-medium">Tucumán, Argentina • 2026</p>
        </footer>
      </body>
    </html>
  );
}
